def Opening():
    print('\n\n')
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print('  SOFTWARE PENGHITUNG METODE NUMERIK KOMPUTASI')
    print('-------------------------------------------------')
    print('Programmer : 1. Lalu Iqbal T (12316025)')
    print('             2. Muhammad Aldi F (12316049)')
    print('             3. Adur (12317045)')
    print('-------------------------------------------------')
    print(' Last Updated: 25 November 2019')
    print(' Contact : aldimfirdaus2@gmail.com')
    print('           lal25uiqbal@gmail.com')
    print('           adurputra@gmail.com')
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')